// Mock schemes data
export const mockSchemes = [
  {
    _id: '1',
    name: 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
    description: 'Income support scheme for farmers providing ₹6000 per year in three installments directly to bank accounts.',
    benefits: '₹6000 per year (₹2000 every 4 months)',
    category: 'Farmers',
    schemeType: 'Central',
    eligibility: {
      minAge: 18,
      occupations: ['Farmer'],
    },
    documents: ['Aadhaar Card', 'Bank Account Details', 'Land Ownership Documents'],
    applicationLink: 'https://pmkisan.gov.in/',
    isActive: true,
  },
  {
    _id: '2',
    name: 'Ayushman Bharat - PM-JAY',
    description: 'Health insurance scheme providing coverage of ₹5 lakh per family per year for hospitalization.',
    benefits: 'Health coverage up to ₹5 lakh per family per year',
    category: 'Health',
    schemeType: 'Central',
    eligibility: {
      maxIncome: 500000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
    },
    documents: ['Aadhaar Card', 'Income Certificate', 'Ration Card'],
    applicationLink: 'https://pmjay.gov.in/',
    isActive: true,
  },
  {
    _id: '3',
    name: 'Pradhan Mantri Awas Yojana (PMAY)',
    description: 'Housing scheme for urban poor providing financial assistance for construction or purchase of houses.',
    benefits: 'Subsidy on home loans and credit-linked subsidies',
    category: 'Housing',
    schemeType: 'Central',
    eligibility: {
      minAge: 21,
      maxAge: 70,
      maxIncome: 1800000,
    },
    documents: ['Aadhaar Card', 'Income Certificate', 'Property Documents', 'Bank Statement'],
    applicationLink: 'https://pmaymis.gov.in/',
    isActive: true,
  },
  {
    _id: '4',
    name: 'Beti Bachao Beti Padhao',
    description: 'Scheme to address declining Child Sex Ratio and promote education of girl child.',
    benefits: 'Financial assistance for education and awareness campaigns',
    category: 'Women',
    schemeType: 'Central',
    eligibility: {
      maxAge: 10,
      gender: 'Female',
    },
    documents: ['Birth Certificate', 'Aadhaar Card', 'Bank Account Details'],
    applicationLink: 'https://wcd.nic.in/bbbp-schemes',
    isActive: true,
  },
  {
    _id: '5',
    name: 'Pradhan Mantri Mudra Yojana',
    description: 'Provides loans up to ₹10 lakh to non-corporate, non-farm small/micro enterprises.',
    benefits: 'Collateral-free loans up to ₹10 lakh',
    category: 'Startup/MSME',
    schemeType: 'Central',
    eligibility: {
      minAge: 18,
      occupations: ['Self-Employed', 'Entrepreneur', 'Small Business Owner'],
    },
    documents: ['Aadhaar Card', 'PAN Card', 'Business Plan', 'Bank Statement'],
    applicationLink: 'https://www.mudra.org.in/',
    isActive: true,
  },
  {
    _id: '6',
    name: 'National Pension Scheme (NPS)',
    description: 'Voluntary retirement savings scheme designed to enable systematic savings for old age.',
    benefits: 'Pension benefits after retirement with tax benefits',
    category: 'Senior Citizens',
    schemeType: 'Central',
    eligibility: {
      minAge: 18,
      maxAge: 70,
    },
    documents: ['Aadhaar Card', 'PAN Card', 'Bank Account Details', 'Address Proof'],
    applicationLink: 'https://www.npscra.nsdl.co.in/',
    isActive: true,
  },
  {
    _id: '7',
    name: 'Post Matric Scholarship for SC Students',
    description: 'Financial assistance to SC students studying at post-matriculation stage.',
    benefits: 'Maintenance allowance and course fees',
    category: 'Education',
    schemeType: 'Central',
    eligibility: {
      minAge: 16,
      maxAge: 35,
      maxIncome: 250000,
      categories: ['SC'],
    },
    documents: ['Aadhaar Card', 'Caste Certificate', 'Income Certificate', 'Mark Sheets'],
    applicationLink: 'https://scholarships.gov.in/',
    isActive: true,
  },
  {
    _id: '8',
    name: 'Atal Pension Yojana (APY)',
    description: 'Pension scheme primarily for workers in unorganized sector.',
    benefits: 'Guaranteed pension of ₹1000 to ₹5000 per month after 60 years',
    category: 'Financial Assistance',
    schemeType: 'Central',
    eligibility: {
      minAge: 18,
      maxAge: 40,
    },
    documents: ['Aadhaar Card', 'Bank Account Details', 'Mobile Number'],
    applicationLink: 'https://www.npscra.nsdl.co.in/',
    isActive: true,
  },
];

export const categories = [
  'All',
  'Health',
  'Education',
  'Women',
  'Farmers',
  'Senior Citizens',
  'Startup/MSME',
  'Housing',
  'Employment',
  'Financial Assistance',
];

export const states = [
  'Andhra Pradesh',
  'Bihar',
  'Delhi',
  'Gujarat',
  'Haryana',
  'Karnataka',
  'Kerala',
  'Maharashtra',
  'Punjab',
  'Rajasthan',
  'Tamil Nadu',
  'Uttar Pradesh',
  'West Bengal',
];